### ISSUE TITLE
Website: Element search.

### ISSUE THREAD

**Issue by zoomlogo** [PyGamer0/flax#38]
New idea, documentation will be in the repository.

The website will be like APLCart.

- [x] Import `icfs` regular.
- [x] Import defined.nvim colorscheme.
- [x] Get JS running.
- [x] elements.txt -> yaml
- [x] Load the elements.json
- [x] List and sort the element.
- [x] Make it searchable.

**Comment by Steffan153** [comment]
This will be much easier if we have all the elements in a YAML or JSON, and then auto-generate the TXT based on it.

**Comment by zoomlogo** [comment]
@Steffan153  @chunkybanana is helping me to convert the txt to a yaml :)

**Comment by Steffan153** [comment]
https://github.com/PyGamer0/flax/pulls/56

**Comment by Steffan153** [comment]
It is much easier to have the element search use the JSON, because JS has builtins for that, just `JSON.parse` instead of having to import libraries to parse a YAML.

**Comment by zoomlogo** [comment]
@Steffan153  ok i will use json then
